#!/bin/bash

#  print
#  declare -f make_log make_run | tee run_make.sh
#  bash run_make.sh

mkdir -p log

cmd=" $(printf ' %s ' "$*") "

func='make_run() { report %s; }'
func="$(printf "${func}" "$*" )"
eval " $func "
make_log() { tee log/make.out 2>&1; };
make_pipe() { make_run 2>&1 | make_log; }

{
  declare -f make_run make_log make_pipe;
  echo;
  echo "make_pipe;";
} | tee run_make.sh >/dev/null

exit 0;

#    
#    {
#    declare -f make_run make_log;
#    
#    echo "make_run | make_log"
#    } | tee run_make.sh
#    
exit 0;

nlnl=$'\n\n';
func="${nlnl}${func}${nlnl}"
eval "$func";

make_do() {
  make_run 2>&1 | make_log;
};

{
  echo
  declare -f "make_run"
  echo
  declare -f "make_log"
  echo
  declare -f "make_do"
  echo
} | tee run_make.sh



  



else
fi
